namespace Grillisoft.Tools.DatabaseDeploy.PostgreSql.Ddl;

/// <summary>
/// One column of a table, as far as writing its definition is concerned.
/// </summary>
/// <param name="Identity">
/// <c>a</c> for <c>GENERATED ALWAYS</c>, <c>d</c> for <c>GENERATED BY DEFAULT</c>, and the space
/// character for a column that is not an identity - the catalog's own spelling.
/// </param>
/// <param name="Generated">
/// <c>s</c> for a stored generated column, the space character otherwise.
/// </param>
/// <param name="IsLocal">
/// False for a column the table only has because it inherits it. Those are written by the
/// <c>INHERITS</c> clause rather than one at a time.
/// </param>
/// <param name="Default">
/// The default expression, already rendered by the server. For a generated column this holds the
/// generation expression instead, which is where the catalog keeps it.
/// </param>
internal sealed record PostgreSqlColumn(
    string Name,
    string Type,
    bool NotNull,
    char Identity,
    char Generated,
    bool IsLocal,
    string Default,
    string CollationSchema,
    string CollationName,
    PostgreSqlSequenceDefinition? IdentitySequence = null);

/// <summary>
/// The parts of a <c>pg_class</c> row the discovery reads once and the scripters need later.
/// </summary>
/// <param name="Persistence">
/// <c>u</c> for an unlogged relation, <c>p</c> for a permanent one - the catalog's own spelling.
/// </param>
/// <param name="PartitionBound">
/// The <c>FOR VALUES ...</c> of a partition, which is written by the <c>ATTACH PARTITION</c> that
/// ties it to its parent rather than by the partition's own <c>CREATE TABLE</c>.
/// </param>
internal sealed record PostgreSqlRelationOptions(
    char Persistence,
    string StorageOptions,
    string PartitionKey,
    string PartitionBound,
    bool IsPartition);

/// <summary>
/// Everything a <c>CREATE TABLE</c> needs, read off the catalog in one place so that turning it
/// into SQL needs no database at all.
/// </summary>
/// <param name="StorageOptions">
/// The table's <c>reloptions</c>, already comma separated. Deliberately not its tablespace: a
/// script carrying the storage of the database it was taken from cannot be replayed anywhere else.
/// </param>
/// <param name="IsPartition">
/// Whether this table is a partition of another. A partition's columns all report themselves as
/// inherited, but unlike an inheriting child's they still have to be written out: it is created as
/// a table of its own and only then attached, so there is nothing to inherit them from yet.
/// </param>
internal sealed record PostgreSqlTableDefinition(
    string Schema,
    string Name,
    IReadOnlyList<PostgreSqlColumn> Columns,
    bool Unlogged,
    string PartitionKey,
    string StorageOptions,
    IReadOnlyList<string> Inherits,
    bool IsPartition = false);
