using Grillisoft.Tools.DatabaseDeploy.SqlServer;

namespace Grillisoft.Tools.DatabaseDeploy.Oracle;

public class OracleScripts(string databaseName, string migrationTableName) : ISqlScripts
{
    public string ExistsSql { get; } = $@"
            SELECT COUNT(*) FROM dba_users WHERE username = '{databaseName}'
        ";

    public string CreateSql { get; } = $@"
            CREATE DATABASE `{databaseName}`
        ";

    public string GetSql { get; } =
        $"SELECT `name`, `deployed_utc`, `user_name`, `hash` FROM `{migrationTableName}` ORDER BY `id` ASC";
    public string AddSql { get; } =
        $@"INSERT INTO `{migrationTableName}`(`name`, `deployed_utc`, `user_name`, `hash`)
                     VALUES(@name, @deployed_utc, @user, @hash)";
    public string RemoveSql { get; } =
        $"DELETE FROM `{migrationTableName}` WHERE `name` = @name";

    public string InitSql { get; } = $@"
            CREATE TABLE {migrationTableName} (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name NVARCHAR2(255),
                deployed_utc TIMESTAMP,
                user_name NVARCHAR2(100),
                hash CHAR(32),
                CONSTRAINT unique_migration_name UNIQUE (name)
            );
        ";
    public string ClearSql { get; } = $@"
            DECLARE
                v_table_count NUMBER;
            BEGIN
                SELECT COUNT(*)
                INTO v_table_count
                FROM user_tables
                WHERE table_name = '{migrationTableName}';

                IF v_table_count > 0 THEN
                    EXECUTE IMMEDIATE 'DROP TABLE {migrationTableName}';
                END IF;
            END;
        ";
}