using Grillisoft.Tools.DatabaseDeploy.SqlServer;

namespace Grillisoft.Tools.DatabaseDeploy.Oracle;

public class OracleScripts(string databaseName, string migrationTableName) : ISqlScripts
{
    public string SetSchemaSql { get; } = $"SET SCHEMA {databaseName.ToUpperInvariant()}";
    
    public string ExistsSql { get; } = $@"
        SELECT CAST(COUNT(*) as INT) AS count FROM all_users WHERE username = '{databaseName.ToUpperInvariant()}'
        ";

    public string CreateSql { get; } = $@"
            CREATE USER {databaseName} IDENTIFIED BY ""{databaseName}""
                           DEFAULT TABLESPACE users
                           QUOTA UNLIMITED ON users
        ";

    public string GrantSql { get; } = $@"
            GRANT CREATE MATERIALIZED VIEW,
                  CREATE PROCEDURE,
                  CREATE SEQUENCE,
                  CREATE SESSION,
                  CREATE SYNONYM,
                  CREATE TABLE,
                  CREATE TRIGGER,
                  CREATE TYPE,
                  CREATE VIEW
              TO {databaseName};
        ";
    
    public string GetSql { get; } =
        $"SELECT name, deployed_utc, user_name, hash FROM {migrationTableName} ORDER BY id ASC";
    public string AddSql { get; } =
        $@"INSERT INTO {migrationTableName}(name, deployed_utc, user_name, hash)
                     VALUES(:name, :deployed_utc, :user_name, :hash)";
    public string RemoveSql { get; } =
        $"DELETE FROM {migrationTableName} WHERE name = :name";

    public string InitSql { get; } = $@"
            CREATE TABLE {migrationTableName} (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name NVARCHAR2(255),
                deployed_utc TIMESTAMP WITH TIME ZONE,
                user_name NVARCHAR2(100),
                hash CHAR(32),
                CONSTRAINT unique_migration_name UNIQUE (name)
            )
        ";

    public string MigrationTableExistsSql { get; } = $@"
            SELECT CAST(COUNT(*) AS INT) AS count
            FROM user_tables
            WHERE table_name = '{migrationTableName}'
        ";
    
    public string ClearSql { get; } = $@"
            DROP TABLE {migrationTableName}
        ";
}