using System.IO.Abstractions.TestingHelpers;
using System.Text;
using Grillisoft.Tools.DatabaseDeploy.Abstractions;
using Grillisoft.Tools.DatabaseDeploy.Tests;
using Grillisoft.Tools.DatabaseDeploy.Tests.Databases;
using Npgsql;

namespace Grillisoft.Tools.DatabaseDeploy.PostgreSql.Tests.Ddl;

/// <summary>
/// End to end check of the schema DDL generation: build a database that uses the features a real
/// application database uses, script it, wipe it and replay the script through the very parser
/// dbdeploy uses at deploy time. Whatever comes back has to match what was there before.
/// </summary>
/// <remarks>
/// Shares <see cref="PostgreSqlFixture"/> with <see cref="PostgreSqlDatabaseTests"/> - one
/// container for the whole project - so the migration cases it inherits run a second time against
/// the same database. They are safe to repeat: every case starts by clearing and re-creating the
/// migrations table, and <c>[NotInParallel]</c> keeps them off each other.
/// </remarks>
[ClassDataSource<PostgreSqlFixture>(Shared = SharedType.PerAssembly)]
[InheritsTests]
public class PostgreSqlSchemaDdlTests : DatabaseTest<PostgreSqlDatabase>
{
    public PostgreSqlSchemaDdlTests(PostgreSqlFixture fixture)
        : base(fixture)
    {
    }

    protected override IDatabaseFactory CreateDatabaseFactory()
    {
        return new PostgreSqlDatabaseFactory(
            new PostgreSqlScriptParser(),
            this.GlobalSettingsOptions,
            this.LoggerFactory);
    }

    protected override string ProviderName => PostgreSqlDatabaseFactory.ProviderName;

    /// <summary>
    /// Everything here exists because it breaks a generator that does the obvious thing: a schema
    /// that is not public alongside one that is, the three shapes of user defined type, an identity
    /// column (whose sequence must not be scripted) next to a serial one (whose sequence must),
    /// two tables referencing each other, a generated column, a partitioned table, a view on a view,
    /// a function returning a table's row type, an extension (whose objects must not be scripted),
    /// and literals holding a quote and a semicolon.
    /// </summary>
    private static readonly string[] Schema =
    [
        "CREATE EXTENSION IF NOT EXISTS pgcrypto",
        "CREATE SCHEMA app",
        "CREATE TYPE app.mood AS ENUM ('sad', 'ok', 'happy')",
        "CREATE TYPE app.address AS (street text, city text)",
        "CREATE DOMAIN app.positive AS integer CONSTRAINT positive_check CHECK (VALUE > 0)",
        "CREATE SEQUENCE app.order_seq START WITH 100 INCREMENT BY 5",
        """
        CREATE TABLE app.customer (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name text NOT NULL,
          email text,
          rating app.positive,
          feeling app.mood DEFAULT 'ok',
          home app.address,
          tags text[],
          last_order_id integer,
          note text DEFAULT 'careful: it''s got a ; in it',
          CONSTRAINT uq_customer_email UNIQUE (email)
        )
        """,
        """
        CREATE TABLE app.orders (
          id serial PRIMARY KEY,
          customer_id integer NOT NULL,
          total numeric(10,2) DEFAULT 0 NOT NULL,
          total_with_tax numeric(12,2) GENERATED ALWAYS AS (total * 1.22) STORED,
          reference integer DEFAULT nextval('app.order_seq') NOT NULL,
          CONSTRAINT ck_orders_total CHECK ((total >= (0)::numeric)),
          CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES app.customer(id)
        )
        """,
        // the mutual reference: no ordering of inline constraints can survive this
        "ALTER TABLE app.customer ADD CONSTRAINT fk_customer_last_order FOREIGN KEY (last_order_id) REFERENCES app.orders(id)",
        "CREATE INDEX ix_orders_big ON app.orders (total) WHERE (total > (100)::numeric)",
        "CREATE INDEX ix_customer_lower_name ON app.customer (lower(name))",
        """
        CREATE FUNCTION app.fn_tax(amount numeric) RETURNS numeric
        LANGUAGE sql IMMUTABLE
        AS $$ SELECT amount * 0.22 $$
        """,
        // a function whose return type is a table's row type: it can only be created after the table
        """
        CREATE FUNCTION app.fn_customers() RETURNS SETOF app.customer
        LANGUAGE sql STABLE
        AS $$ SELECT * FROM app.customer $$
        """,
        """
        CREATE FUNCTION app.trg_set_total() RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
          IF NEW.total IS NULL THEN
            NEW.total := 0;
          END IF;
          RETURN NEW;
        END;
        $$
        """,
        """
        CREATE TRIGGER trg_orders_total BEFORE INSERT ON app.orders
        FOR EACH ROW EXECUTE FUNCTION app.trg_set_total()
        """,
        """
        CREATE VIEW app.v_order_totals AS
        SELECT o.id AS order_id, o.customer_id, o.total, app.fn_tax(o.total) AS tax
        FROM app.orders o
        """,
        // a view on a view
        "CREATE VIEW app.v_big_orders AS SELECT order_id, total FROM app.v_order_totals WHERE total > 100",
        """
        CREATE MATERIALIZED VIEW app.mv_customer_orders AS
        SELECT c.id, count(o.id) AS orders
        FROM app.customer c LEFT JOIN app.orders o ON o.customer_id = c.id
        GROUP BY c.id
        """,
        "CREATE UNIQUE INDEX ux_mv_customer ON app.mv_customer_orders (id)",
        """
        CREATE TABLE app.measurement (
          id integer NOT NULL,
          taken date NOT NULL,
          value numeric
        ) PARTITION BY RANGE (taken)
        """,
        """
        CREATE TABLE app.measurement_2024 PARTITION OF app.measurement
        FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')
        """,
        // a table in public, to prove CREATE SCHEMA public is never written
        "CREATE TABLE public.audit_log (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, message text)",
        "COMMENT ON TABLE app.customer IS 'The customer''s master data'",
        "COMMENT ON COLUMN app.customer.name IS 'Full name; don''t truncate'",
    ];

    [Test]
    [Category(TestCategories.Docker)]
    public async Task GenerateSchemaDdl_ShouldProduceAScriptThatRebuildsTheDatabase(CancellationToken cancellationToken)
    {
        // arrange
        var sut = await this.CreateDatabase(cancellationToken);
        await DropEverything();

        foreach (var statement in Schema)
            await sut.RunScript(statement, CancellationToken.None);

        var expectedRelations = await GetRelations();
        var expectedColumns = await GetColumns();
        var expectedConstraints = await GetConstraints();
        var expectedIndexes = await GetIndexes();
        var expectedTriggers = await GetTriggers();
        var expectedRoutines = await GetRoutines();
        var expectedTypes = await GetTypes();
        var expectedComments = await GetComments();

        expectedRelations.Should().NotBeEmpty();
        expectedConstraints.Should().NotBeEmpty();
        expectedComments.Should().NotBeEmpty();

        // act
        var script = await GenerateScript(sut);
        TestContext.Current?.OutputWriter.WriteLine(script);

        await DropEverything();
        (await GetRelations()).Should().BeEmpty("the database must be wiped before replaying the script");

        await Replay(sut, script);

        // assert
        (await GetRelations()).Should().BeEquivalentTo(expectedRelations);
        (await GetColumns()).Should().BeEquivalentTo(expectedColumns);
        (await GetConstraints()).Should().BeEquivalentTo(expectedConstraints);
        (await GetIndexes()).Should().BeEquivalentTo(expectedIndexes);
        (await GetTriggers()).Should().BeEquivalentTo(expectedTriggers);
        (await GetRoutines()).Should().BeEquivalentTo(expectedRoutines);
        (await GetTypes()).Should().BeEquivalentTo(expectedTypes);
        (await GetComments()).Should().BeEquivalentTo(expectedComments);

        // public exists in every new database, exactly as dbo does on SQL Server
        script.Should().NotContain("CREATE SCHEMA public");

        // the roles of the database it was taken from cannot be assumed to exist where it is replayed
        script.Should().NotContain("OWNER TO");

        // a script carrying the storage of the database it was taken from cannot be replayed elsewhere
        script.Should().NotContain("TABLESPACE");

        // dbdeploy owns the migrations table; a script that recreates it fights the tool
        script.Should().NotContain("__Migrations");

        // the sequence behind an identity column is created by the column, not on its own
        script.Should().NotContain("CREATE SEQUENCE app.customer_id_seq");

        // pgcrypto's own functions belong to the extension and must not be scripted
        script.Should().NotContain("gen_salt");
    }

    private static async Task<string> GenerateScript(PostgreSqlDatabase database)
    {
        using var stream = new MemoryStream();
        await using (var writer = new StreamWriter(stream, new UTF8Encoding(false), 4096, true))
        {
            await database.GenerateSchemaDdl(writer, CancellationToken.None);
        }

        return Encoding.UTF8.GetString(stream.ToArray());
    }

    /// <summary>
    /// Replays the script the way the deploy command does. The PostgreSQL parser yields the whole
    /// file as one statement, so a failure is one enormous blob: everything the server said about
    /// where it went wrong has to be put in the message, or there is no finding it.
    /// </summary>
    private static async Task Replay(PostgreSqlDatabase database, string script)
    {
        var fileSystem = new MockFileSystem();
        fileSystem.AddFile("/scripts/init.sql", new MockFileData(script));

        var parser = new PostgreSqlScriptParser();

        await foreach (var statement in parser.Parse(fileSystem.FileInfo.New("/scripts/init.sql"), CancellationToken.None))
        {
            try
            {
                await database.RunScript(statement, CancellationToken.None);
            }
            catch (PostgresException ex)
            {
                throw new InvalidOperationException(
                    $"The generated script failed with {ex.SqlState}: {ex.MessageText}{Environment.NewLine}" +
                    $"  where: {ex.Where}{Environment.NewLine}" +
                    $"  at character {ex.Position}: {Excerpt(statement, ex.Position)}", ex);
            }
        }
    }

    /// <summary>The statement around the character the server pointed at.</summary>
    private static string Excerpt(string statement, int position)
    {
        if (position <= 0 || position > statement.Length)
            return string.Empty;

        var from = Math.Max(0, position - 200);
        var to = Math.Min(statement.Length, position + 200);
        return statement[from..to];
    }

    private async Task<List<string>> Read(string sql)
    {
        await using var connection = new NpgsqlConnection(this.ConnectionString);
        await connection.OpenAsync();

        await using var command = connection.CreateCommand();
        command.CommandText = sql;

        var result = new List<string>();
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
            result.Add(reader.IsDBNull(0) ? string.Empty : reader.GetString(0));

        return result;
    }

    private Task<List<string>> GetRelations() => Read("""
        SELECT concat_ws('|', n.nspname, c.relname, c.relkind, c.relpersistence)
        FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind IN ('r','p','v','m','S')
          AND n.nspname NOT IN ('pg_catalog', 'information_schema')
          AND n.nspname NOT LIKE 'pg\_%'
          AND c.relname <> '__Migrations'
          AND NOT EXISTS (SELECT 1 FROM pg_catalog.pg_depend e
                          WHERE e.classid = 'pg_class'::regclass AND e.objid = c.oid AND e.deptype = 'e')
        ORDER BY 1
        """);

    /// <summary>
    /// The column definition down to the parts a generated script has to reproduce exactly: the
    /// type, nullability, the default, whether it is an identity and whether it is generated.
    /// </summary>
    private Task<List<string>> GetColumns() => Read("""
        SELECT concat_ws('|', n.nspname, c.relname, a.attname,
                         pg_catalog.format_type(a.atttypid, a.atttypmod),
                         a.attnotnull, a.attidentity, a.attgenerated,
                         COALESCE(pg_catalog.pg_get_expr(ad.adbin, ad.adrelid), '-'))
        FROM pg_catalog.pg_attribute a
        JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        LEFT JOIN pg_catalog.pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
        WHERE a.attnum > 0 AND NOT a.attisdropped
          AND c.relkind IN ('r','p','v','m')
          AND n.nspname NOT IN ('pg_catalog', 'information_schema')
          AND c.relname <> '__Migrations'
        ORDER BY 1
        """);

    private Task<List<string>> GetConstraints() => Read("""
        SELECT concat_ws('|', n.nspname, c.relname, k.conname, k.contype,
                         pg_catalog.pg_get_constraintdef(k.oid))
        FROM pg_catalog.pg_constraint k
        JOIN pg_catalog.pg_class c ON c.oid = k.conrelid
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
          AND c.relname <> '__Migrations'
        ORDER BY 1
        """);

    /// <summary>
    /// The pg_toast schema is excluded like the other system ones: the name of a toast index
    /// carries the oid of the table it belongs to, so it is never the same twice and comparing it
    /// would only assert that the oid counter moved.
    /// </summary>
    private Task<List<string>> GetIndexes() => Read("""
        SELECT n.nspname || '|' || pg_catalog.pg_get_indexdef(i.indexrelid)
        FROM pg_catalog.pg_index i
        JOIN pg_catalog.pg_class c ON c.oid = i.indexrelid
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
          AND n.nspname NOT LIKE 'pg\_%'
          AND c.relname NOT LIKE '\_\_Migrations%'
        ORDER BY 1
        """);

    private Task<List<string>> GetTriggers() => Read("""
        SELECT n.nspname || '|' || pg_catalog.pg_get_triggerdef(t.oid, true)
        FROM pg_catalog.pg_trigger t
        JOIN pg_catalog.pg_class c ON c.oid = t.tgrelid
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE NOT t.tgisinternal AND n.nspname NOT IN ('pg_catalog', 'information_schema')
        ORDER BY 1
        """);

    /// <summary>
    /// Routines by signature and result rather than by body: the body comes back from the server
    /// verbatim, so comparing it would only assert that a string survived a round trip.
    /// </summary>
    private Task<List<string>> GetRoutines() => Read("""
        SELECT concat_ws('|', n.nspname, p.proname,
                         pg_catalog.pg_get_function_identity_arguments(p.oid),
                         pg_catalog.pg_get_function_result(p.oid), p.prokind, l.lanname)
        FROM pg_catalog.pg_proc p
        JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
        JOIN pg_catalog.pg_language l ON l.oid = p.prolang
        WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
          AND NOT EXISTS (SELECT 1 FROM pg_catalog.pg_depend e
                          WHERE e.classid = 'pg_proc'::regclass AND e.objid = p.oid AND e.deptype = 'e')
        ORDER BY 1
        """);

    private Task<List<string>> GetTypes() => Read("""
        SELECT concat_ws('|', n.nspname, t.typname, t.typtype,
                         COALESCE((SELECT string_agg(e.enumlabel, ',' ORDER BY e.enumsortorder)
                                   FROM pg_catalog.pg_enum e WHERE e.enumtypid = t.oid), ''))
        FROM pg_catalog.pg_type t
        JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typtype IN ('e','c','d','r')
          AND n.nspname NOT IN ('pg_catalog', 'information_schema')
          AND NOT EXISTS (SELECT 1 FROM pg_catalog.pg_class c
                          WHERE c.oid = t.typrelid AND c.relkind <> 'c')
          AND NOT EXISTS (SELECT 1 FROM pg_catalog.pg_depend e
                          WHERE e.classid = 'pg_type'::regclass AND e.objid = t.oid AND e.deptype = 'e')
        ORDER BY 1
        """);

    private Task<List<string>> GetComments() => Read("""
        SELECT o.type || '|' || o.identity || '|' || d.description
        FROM pg_catalog.pg_description d
        CROSS JOIN LATERAL pg_catalog.pg_identify_object(d.classoid, d.objoid, d.objsubid) o
        WHERE o.schema IS NOT NULL
          AND o.schema NOT IN ('pg_catalog', 'information_schema')
          AND o.identity NOT LIKE '%__Migrations%'
        ORDER BY 1
        """);

    /// <summary>
    /// Wipes the database. Dropping in dependency order is exactly the problem this test is about,
    /// and here it does not need solving: the schemas go with CASCADE and public is rebuilt.
    /// </summary>
    private async Task DropEverything()
    {
        await using var connection = new NpgsqlConnection(this.ConnectionString);
        await connection.OpenAsync();

        var schemas = new List<string>();
        await using (var command = connection.CreateCommand())
        {
            command.CommandText = """
                SELECT n.nspname FROM pg_catalog.pg_namespace n
                WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
                  AND n.nspname NOT LIKE 'pg\_%'
                """;

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
                schemas.Add(reader.GetString(0));
        }

        foreach (var schema in schemas)
        {
            await using var drop = connection.CreateCommand();
            drop.CommandText = $"DROP SCHEMA IF EXISTS \"{schema}\" CASCADE";
            await drop.ExecuteNonQueryAsync();
        }

        await using var recreate = connection.CreateCommand();
        recreate.CommandText = "CREATE SCHEMA IF NOT EXISTS public; DROP EXTENSION IF EXISTS pgcrypto CASCADE";
        await recreate.ExecuteNonQueryAsync();
    }
}
