using Grillisoft.Tools.DatabaseDeploy.PostgreSql.Ddl;

namespace Grillisoft.Tools.DatabaseDeploy.PostgreSql.Tests.Ddl;

/// <summary>
/// <c>CREATE TABLE</c> is the one statement PostgreSQL has no function to produce, so it is the one
/// this tool has to get right on its own. Reading and rendering are separate methods precisely so
/// that the half where all the decisions are needs no server.
/// </summary>
public class PostgreSqlTableScripterTests
{
    private static PostgreSqlColumn Column(
        string name,
        string type,
        bool notNull = false,
        char identity = ' ',
        char generated = ' ',
        bool isLocal = true,
        string @default = "",
        string collationSchema = "",
        string collationName = "",
        PostgreSqlSequenceDefinition? identitySequence = null)
        => new(name, type, notNull, identity, generated, isLocal, @default,
            collationSchema, collationName, identitySequence);

    private static PostgreSqlTableDefinition Table(
        params PostgreSqlColumn[] columns)
        => new("app", "customer", columns, Unlogged: false, PartitionKey: "", StorageOptions: "", Inherits: []);

    private static string Render(PostgreSqlTableDefinition table)
        => PostgreSqlTableScripter.Render(table).Replace("\r\n", "\n", StringComparison.Ordinal);

    /// <summary>
    /// Every identifier is quoted, always. PostgreSQL folds an unquoted name to lower case, so a
    /// table called Orders only survives a round trip if it is quoted every time it is written.
    /// </summary>
    [Test]
    public void Render_ShouldQuoteEveryIdentifier()
    {
        var sql = Render(Table(Column("id", "integer", notNull: true)));

        sql.Should().Be("""
            CREATE TABLE "app"."customer" (
                "id" integer NOT NULL
            )
            """.Replace("\r\n", "\n", StringComparison.Ordinal));
    }

    [Test]
    public void Render_ShouldWriteTheDefaultExpressionAsTheServerGaveIt()
    {
        var sql = Render(Table(Column("note", "text", @default: "'it''s got a ; in it'::text")));

        sql.Should().Contain("\"note\" text DEFAULT 'it''s got a ; in it'::text");
    }

    [Test]
    [Arguments('a', "ALWAYS")]
    [Arguments('d', "BY DEFAULT")]
    public void Render_ShouldWriteAnIdentityColumnAsGenerated(char identity, string expected)
    {
        var sql = Render(Table(Column("id", "integer", notNull: true, identity: identity)));

        sql.Should().Contain($"\"id\" integer GENERATED {expected} AS IDENTITY NOT NULL");
    }

    /// <summary>
    /// An identity whose sequence is entirely default needs no option list; writing one would be
    /// noise in every generated file.
    /// </summary>
    [Test]
    public void Render_WhenTheIdentitySequenceIsDefault_ShouldWriteNoOptions()
    {
        var sequence = new PostgreSqlSequenceDefinition("integer", 1, 1, 1, int.MaxValue, 1, false);
        var sql = Render(Table(Column("id", "integer", identity: 'd', identitySequence: sequence)));

        sql.Should().Contain("GENERATED BY DEFAULT AS IDENTITY").And.NotContain("MAXVALUE");
    }

    [Test]
    public void Render_WhenTheIdentitySequenceIsNotDefault_ShouldWriteItsOptions()
    {
        var sequence = new PostgreSqlSequenceDefinition("integer", 100, 5, 1, int.MaxValue, 1, false);
        var sql = Render(Table(Column("id", "integer", identity: 'a', identitySequence: sequence)));

        sql.Should().Contain("GENERATED ALWAYS AS IDENTITY ( INCREMENT BY 5 START WITH 100 )");
    }

    /// <summary>
    /// The generation expression is kept where a default would be, and the two are exclusive: a
    /// generated column that also carried DEFAULT would not parse.
    /// </summary>
    [Test]
    public void Render_ShouldWriteAGeneratedColumnFromItsDefaultExpression()
    {
        var sql = Render(Table(Column("total_with_tax", "numeric(12,2)", generated: 's', @default: "(total * 1.22)")));

        sql.Should().Contain("\"total_with_tax\" numeric(12,2) GENERATED ALWAYS AS ((total * 1.22)) STORED")
           .And.NotContain("DEFAULT");
    }

    [Test]
    public void Render_ShouldWriteACollationOnlyWhenTheColumnHasOneOfItsOwn()
    {
        var sql = Render(Table(
            Column("name", "text", collationSchema: "public", collationName: "en_US"),
            Column("email", "text")));

        sql.Should().Contain("\"name\" text COLLATE \"public\".\"en_US\"")
           .And.Contain("\"email\" text\n");
    }

    /// <summary>
    /// A column the table only inherits is created by the INHERITS clause. Declaring it again is
    /// an error, not a duplicate.
    /// </summary>
    [Test]
    public void Render_ShouldLeaveOutInheritedColumns()
    {
        var table = Table(Column("id", "integer", isLocal: false), Column("extra", "text")) with
        {
            Inherits = ["\"app\".\"base\""],
        };

        var sql = Render(table);

        sql.Should().NotContain("\"id\"")
           .And.Contain("\"extra\" text")
           .And.Contain("INHERITS (\"app\".\"base\")");
    }

    /// <summary>
    /// A partition is the exception: its columns all report themselves as inherited, but it is
    /// created on its own and attached only afterwards, so it has nothing to inherit them from yet.
    /// </summary>
    [Test]
    public void Render_WhenTheTableIsAPartition_ShouldStillDeclareEveryColumn()
    {
        var table = Table(Column("id", "integer", isLocal: false), Column("taken", "date", isLocal: false)) with
        {
            IsPartition = true,
        };

        Render(table).Should().Contain("\"id\" integer").And.Contain("\"taken\" date");
    }

    [Test]
    public void Render_ShouldWriteThePartitionKey()
    {
        var table = Table(Column("taken", "date", notNull: true)) with { PartitionKey = "RANGE (taken)" };

        Render(table).Should().Contain("PARTITION BY RANGE (taken)");
    }

    [Test]
    public void Render_ShouldWriteUnloggedAndStorageOptions()
    {
        var table = Table(Column("id", "integer")) with { Unlogged = true, StorageOptions = "fillfactor=70" };

        var sql = Render(table);

        sql.Should().StartWith("CREATE UNLOGGED TABLE").And.Contain("WITH (fillfactor=70)");
    }

    /// <summary>
    /// A script carrying the storage of the database it was taken from cannot be replayed
    /// anywhere else, which is why the tablespace is never read in the first place.
    /// </summary>
    [Test]
    public void Render_ShouldNeverWriteATablespace()
    {
        Render(Table(Column("id", "integer"))).Should().NotContain("TABLESPACE");
    }

    /// <summary>
    /// A partition of a partitioned table declares no columns of its own when it is written as a
    /// plain child, so the statement has to stay valid with an empty column list.
    /// </summary>
    [Test]
    public void Render_WhenThereAreNoLocalColumns_ShouldStillProduceAValidStatement()
    {
        var table = Table(Column("id", "integer", isLocal: false)) with { Inherits = ["\"app\".\"base\""] };

        Render(table).Should().Be("CREATE TABLE \"app\".\"customer\" ()\nINHERITS (\"app\".\"base\")");
    }
}
