using System.IO.Abstractions.TestingHelpers;
using System.Text;
using AwesomeAssertions;
using DotNet.Testcontainers.Containers;
using Grillisoft.Tools.DatabaseDeploy.Abstractions;
using Grillisoft.Tools.DatabaseDeploy.Tests;
using Grillisoft.Tools.DatabaseDeploy.Tests.Databases;
using Oracle.ManagedDataAccess.Client;
using Testcontainers.Oracle;
using Xunit;
using Xunit.Abstractions;

namespace Grillisoft.Tools.DatabaseDeploy.Oracle.Tests.Ddl;

/// <summary>
/// End to end check of the schema DDL generation: build a schema that uses the features a real
/// application database uses, script it, wipe the schema and replay the script through the very
/// parser dbdeploy uses at deploy time. Whatever comes back has to match what was there before.
/// </summary>
public class OracleSchemaDdlTests : DatabaseTest<OracleDatabase, OracleContainer>
{
    private readonly ITestOutputHelper _output;

    public OracleSchemaDdlTests(ITestOutputHelper output)
        : base(new OracleBuilder().Build(), output)
    {
        _output = output;
    }

    protected override IDictionary<string, string?> GetConfigurationSettings()
    {
        var ret = base.GetConfigurationSettings();
        ret.Add("databases:test:schema", "oracle");
        ret.Add("databases:test:migrationTable", "MIGRATIONS");
        return ret;
    }

    protected override IDatabaseFactory CreateDatabaseFactory()
    {
        return new OracleDatabaseFactory(
            new OracleScriptParser(),
            this.GlobalSettingsOptions,
            this.LoggerFactory);
    }

    protected override string ProviderName => OracleDatabaseFactory.ProviderName;

    /// <summary>
    /// Everything here exists because it used to break the generator: object types and their
    /// bodies, a nested table (whose storage table must not be scripted), an identity column (whose
    /// sequence must not be scripted), a materialized view (whose container table must not be
    /// scripted), a function based index, a foreign key that has to land after both tables, two
    /// packages calling each other, and literals holding quotes and SQL keywords.
    /// </summary>
    private static readonly string[] Schema =
    [
        """
        CREATE TYPE address_t AS OBJECT (street VARCHAR2(100), city VARCHAR2(50))
        """,
        """
        CREATE TYPE tag_list_t AS TABLE OF VARCHAR2(50)
        """,
        """
        CREATE TYPE counter_t AS OBJECT (value NUMBER, MEMBER FUNCTION doubled RETURN NUMBER)
        """,
        """
        CREATE TYPE BODY counter_t AS
          MEMBER FUNCTION doubled RETURN NUMBER IS
          BEGIN
            RETURN value * 2;
          END;
        END;
        """,
        """
        CREATE SEQUENCE order_seq START WITH 100 INCREMENT BY 1
        """,
        """
        CREATE TABLE customer (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR2(100) NOT NULL,
          email VARCHAR2(200),
          address address_t,
          tags tag_list_t,
          created_on DATE DEFAULT SYSDATE,
          CONSTRAINT uq_customer_email UNIQUE (email),
          CONSTRAINT ck_customer_name CHECK (LENGTH(name) > 1)
        ) NESTED TABLE tags STORE AS customer_tags
        """,
        """
        CREATE TABLE lookup (
          code VARCHAR2(30),
          label VARCHAR2(100),
          CONSTRAINT pk_lookup PRIMARY KEY (code)
        ) ORGANIZATION INDEX
        """,
        """
        CREATE TABLE orders (
          id NUMBER PRIMARY KEY,
          customer_id NUMBER NOT NULL,
          total NUMBER(10,2) DEFAULT 0,
          note VARCHAR2(400) DEFAULT 'careful: it''s got an ALTER TABLE in it',
          CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customer (id)
        )
        """,
        """
        CREATE INDEX ix_orders_total ON orders (total)
        """,
        """
        CREATE INDEX ix_customer_upper_name ON customer (UPPER(name))
        """,
        """
        CREATE OR REPLACE FUNCTION fn_tax (amount IN NUMBER) RETURN NUMBER
        IS
        BEGIN
          -- don't remove this comment: its apostrophe used to break the parser
          RETURN amount * 0.22;
        END;
        """,
        """
        CREATE OR REPLACE VIEW v_customer_orders AS
        SELECT c.id AS customer_id, c.name, o.id AS order_id, fn_tax(o.total) AS tax
        FROM customer c JOIN orders o ON o.customer_id = c.id
        """,
        """
        CREATE MATERIALIZED VIEW mv_order_totals AS
        SELECT customer_id, SUM(total) AS total FROM orders GROUP BY customer_id
        """,
        """
        CREATE OR REPLACE PROCEDURE pr_add_order (p_customer IN NUMBER, p_total IN NUMBER)
        IS
        BEGIN
          INSERT INTO orders (id, customer_id, total) VALUES (order_seq.NEXTVAL, p_customer, p_total);
        END;
        """,
        """
        CREATE OR REPLACE PACKAGE pkg_alpha AS
          FUNCTION describe RETURN VARCHAR2;
        END pkg_alpha;
        """,
        """
        CREATE OR REPLACE PACKAGE pkg_beta AS
          FUNCTION describe RETURN VARCHAR2;
        END pkg_beta;
        """,
        // pkg_alpha's body calls pkg_beta, so the two bodies and the two specs have to be ordered
        """
        CREATE OR REPLACE PACKAGE BODY pkg_alpha AS
          FUNCTION describe RETURN VARCHAR2 IS
          BEGIN
            RETURN 'alpha then ' || pkg_beta.describe;
          END;
        END pkg_alpha;
        """,
        """
        CREATE OR REPLACE PACKAGE BODY pkg_beta AS
          FUNCTION describe RETURN VARCHAR2 IS
          BEGIN
            RETURN 'beta';
          END;
        END pkg_beta;
        """,
        """
        CREATE OR REPLACE TRIGGER trg_orders_default_total
        BEFORE INSERT ON orders
        FOR EACH ROW
        BEGIN
          IF :NEW.total IS NULL THEN
            :NEW.total := 0;
          END IF;
        END;
        """,
        """
        CREATE SYNONYM syn_customer FOR customer
        """,
        """
        COMMENT ON TABLE customer IS 'The customer''s master data'
        """,
        """
        COMMENT ON COLUMN customer.name IS 'Full name; don''t truncate'
        """,
    ];

    [Fact]
    [Trait(nameof(DockerPlatform), nameof(DockerPlatform.Linux))]
    public async Task GenerateSchemaDdl_ShouldProduceAScriptThatRebuildsTheSchema()
    {
        // arrange
        var sut = await this.CreateDatabase();
        await DropEverything();

        foreach (var statement in Schema)
            await sut.RunScript(statement, CancellationToken.None);

        var expectedObjects = await GetObjects();
        var expectedConstraints = await GetForeignKeys();
        var expectedComments = await GetComments();

        expectedObjects.Should().NotBeEmpty();
        expectedConstraints.Should().NotBeEmpty();

        // act
        var script = await GenerateScript(sut);
        _output.WriteLine(script);

        await DropEverything();
        (await GetObjects()).Should().BeEmpty("the schema must be wiped before replaying the script");

        await Replay(sut, script);

        // assert
        (await GetObjects()).Should().BeEquivalentTo(expectedObjects);
        (await GetForeignKeys()).Should().BeEquivalentTo(expectedConstraints);
        (await GetComments()).Should().BeEquivalentTo(expectedComments);
        (await GetInvalidObjects()).Should().BeEmpty("everything the script creates has to compile");

        // the storage of a nested table and the container of a materialized view belong to their
        // owning object and must not be scripted as tables of their own
        script.Should().NotContain("CREATE TABLE \"CUSTOMER_TAGS\"")
              .And.NotContain("CREATE TABLE \"MV_ORDER_TOTALS\"");

        // a script carrying the tablespace of the database it was taken from cannot be replayed
        // anywhere else
        script.Should().NotContain("TABLESPACE");
    }

    private static async Task<string> GenerateScript(OracleDatabase database)
    {
        using var stream = new MemoryStream();
        await using (var writer = new StreamWriter(stream, new UTF8Encoding(false), 4096, true))
        {
            await database.GenerateSchemaDdl(writer, CancellationToken.None);
        }

        return Encoding.UTF8.GetString(stream.ToArray());
    }

    /// <summary>
    /// Replays the script the way the deploy command does, statement by statement, through the
    /// Oracle script parser.
    /// </summary>
    private async Task Replay(OracleDatabase database, string script)
    {
        var fileSystem = new MockFileSystem();
        fileSystem.AddFile("/scripts/init.sql", new MockFileData(script));

        var parser = new OracleScriptParser();
        var executed = 0;

        await foreach (var statement in parser.Parse(fileSystem.FileInfo.New("/scripts/init.sql"), CancellationToken.None))
        {
            try
            {
                await database.RunScript(statement, CancellationToken.None);
                executed++;
            }
            catch (Exception ex)
            {
                throw new InvalidOperationException(
                    $"Statement {executed + 1} of the generated script failed: {ex.Message}{Environment.NewLine}{statement}", ex);
            }
        }

        _output.WriteLine($"Replayed {executed} statements");
        executed.Should().BeGreaterThan(0);
    }

    private async Task<List<string>> Read(string sql)
    {
        await using var connection = new OracleConnection(this.ConnectionString);
        await connection.OpenAsync();

        await using var command = connection.CreateCommand();
        command.CommandText = sql;

        var result = new List<string>();
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
            result.Add(reader.GetString(0));

        return result;
    }

    /// <summary>
    /// Objects Oracle names itself (SYS_C… constraints, the SYS_FK… index behind a nested table)
    /// carry the object id in their name, so they never come back with the same name after a drop
    /// and recreate. Their presence is still checked, through the object they hang off.
    /// </summary>
    private Task<List<string>> GetObjects() => Read("""
        SELECT o.object_type || ' ' || o.object_name
        FROM user_objects o
        WHERE o.generated = 'N'
          AND o.secondary = 'N'
          AND o.subobject_name IS NULL
          AND o.object_name NOT LIKE 'BIN$%'
          AND o.object_name NOT LIKE 'MLOG$%'
          AND o.object_name NOT LIKE 'SYS\_%' ESCAPE '\'
          AND o.object_name <> 'MIGRATIONS'
        ORDER BY 1
        """);

    private Task<List<string>> GetInvalidObjects() => Read("""
        SELECT o.object_type || ' ' || o.object_name
        FROM user_objects o
        WHERE o.status <> 'VALID'
          AND o.object_name NOT LIKE 'BIN$%'
        ORDER BY 1
        """);

    private Task<List<string>> GetForeignKeys() => Read("""
        SELECT c.constraint_name || ' ' || c.table_name
        FROM user_constraints c
        WHERE c.constraint_type = 'R'
        ORDER BY 1
        """);

    private Task<List<string>> GetComments() => Read("""
        SELECT t.table_name || ' = ' || t.comments FROM user_tab_comments t WHERE t.comments IS NOT NULL
        UNION ALL
        SELECT c.table_name || '.' || c.column_name || ' = ' || c.comments
        FROM user_col_comments c WHERE c.comments IS NOT NULL
        ORDER BY 1
        """);

    /// <summary>
    /// Wipes the schema. Runs more than once because dropping in dependency order is exactly the
    /// problem this test is about, and here it does not need solving.
    /// </summary>
    private async Task DropEverything()
    {
        const string drop = """
            BEGIN
              FOR r IN (SELECT object_name, object_type FROM user_objects
                        WHERE object_type IN ('TABLE','VIEW','MATERIALIZED VIEW','SEQUENCE','SYNONYM',
                                              'PACKAGE','PROCEDURE','FUNCTION','TYPE','TRIGGER','INDEX')
                          AND object_name NOT LIKE 'BIN$%')
              LOOP
                BEGIN
                  IF r.object_type = 'TABLE' THEN
                    EXECUTE IMMEDIATE 'DROP TABLE "' || r.object_name || '" CASCADE CONSTRAINTS PURGE';
                  ELSIF r.object_type = 'TYPE' THEN
                    EXECUTE IMMEDIATE 'DROP TYPE "' || r.object_name || '" FORCE';
                  ELSE
                    EXECUTE IMMEDIATE 'DROP ' || r.object_type || ' "' || r.object_name || '"';
                  END IF;
                EXCEPTION WHEN OTHERS THEN NULL;
                END;
              END LOOP;
            END;
            """;

        await using var connection = new OracleConnection(this.ConnectionString);
        await connection.OpenAsync();

        for (var attempt = 0; attempt < 3; attempt++)
        {
            await using var command = connection.CreateCommand();
            command.CommandText = drop;
            await command.ExecuteNonQueryAsync();
        }

        await using var purge = connection.CreateCommand();
        purge.CommandText = "PURGE RECYCLEBIN";
        await purge.ExecuteNonQueryAsync();
    }
}
