name: Integration Tests
on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches: [main]

env:
  DOTNET_ENVIRONMENT: ci
  PROJECT: src/Grillisoft.Tools.DatabaseDeploy.Cli/Grillisoft.Tools.DatabaseDeploy.Cli.csproj
  
jobs:
  mssql-job:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:9.0
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: 'Y'
          SA_PASSWORD: 'SqlServer2019!'
        ports:
          - 1433:1433
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dotnet restore
        run: dotnet restore

      - name: dbdeploy ci
        run: dotnet run --configuration Release --project $PROJECT -- ci --path examples/mssql-02 -c --branch release/1.1
        
  oracle-job:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:9.0
    services:
      oracle:
        image: gvenzl/oracle-free:latest
        env:
          ORACLE_PASSWORD: 'oracle2019!'
        ports:
          - 1521:1521
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dotnet restore
        run: dotnet restore

      - name: dbdeploy ci
        run: dotnet run --configuration Release --project $PROJECT -- ci --path examples/oracle-01 -c --branch release/1.1

  mariadb-job:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:9.0
    services:
      mariadb:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: mariadb2019!
        ports:
          - 3306:3306
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dotnet restore
        run: dotnet restore

      - name: dbdeploy ci
        run: dotnet run --configuration Release --project $PROJECT -- ci --path examples/mysql-01 -c --branch release/1.1

  postgres-job:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:9.0
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres2019!
        ports:
          - 5432:5432
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dotnet restore
        run: dotnet restore

      - name: dbdeploy ci
        run: dotnet run --configuration Release --project $PROJECT -- ci --path examples/postgres-01 -c --branch release/1.1