name: Integration Tests
on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches: [main]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: SqlServer2019!
        ports:
          - 1433:1433

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dotnet restore
        run: dotnet restore

      - name: Dotnet build
        run: dotnet build --configuration Release
        
      - name: Wait for mssql service
        uses: juliangruber/sleep-action@v2.0.0
        with:
          time: 20s
 
      - name: Run Integration Test
        run: dotnet run --configuration Release --project src/Grillisoft.Tools.DatabaseDeploy.Cli/Grillisoft.Tools.DatabaseDeploy.Cli.csproj -- deploy --path examples/example02 -c
